const copy = {
  en: {
    skip: "Skip to content",
    help: "I need help",
    exit: "Quick exit",
    helpBar: "Free, confidential, 24/7",
    nav: [
      { id: "helplines", label: "Get help" },
      { id: "learn", label: "Learn" },
      { id: "rights", label: "Rights" },
      { id: "document", label: "Private record" },
    ],
    eyebrow: "Free, confidential support",
    heroTitle: "You decide what happens next.",
    heroLine:
      "Nia is for people in Kenya who have faced sexual harassment. Here, you'll learn what it can look like, see your options, and reach a verified line in your own time.",
    ctaReach: "Get help now",
    channelNumber: "1195",
    channelCaption: "GBV helpline",
    channels: [
      { image: "/images/portrait.png", label: "Call" },
      { image: "/images/conversation.png", label: "Talk" },
      { image: "/images/support.png", label: "Care" },
    ],
    iWantTitle: "I want to…",
    paths: [
      {
        id: "helplines",
        title: "Get help now",
        line: "Call a labeled line. You will know who answers.",
      },
      {
        id: "support-someone",
        title: "Support someone I care about",
        line: "If someone tells you what happened, here is how to listen.",
      },
      {
        id: "rights",
        title: "Know my options",
        line: "Source-backed information. Nia does not decide for you.",
      },
      {
        id: "document",
        title: "Keep a private record",
        line: "A private note on your account. Only you can see it.",
      },
      {
        id: "complicated",
        title: "Something complicated happened",
        line: "More than one person, drugs, or pressure from a school or workplace.",
      },
    ],
    howTitle: "How Nia helps",
    howLine: "You decide what happens next, at your own pace.",
    how: [
      {
        title: "Understand what happened",
        line: "Recognise harassment and abuse of power. It is never your fault.",
      },
      {
        title: "Know your rights",
        line: "Kenyan law in plain language, checked against official sources.",
      },
      {
        title: "Keep a private record",
        line: "Write down what happened. Only you can see it unless you share it.",
      },
      {
        title: "Other people are often told to stay quiet",
        line: "You can keep names in your private note. Nia does not compare them with anyone else.",
      },
      {
        title: "Reach verified support",
        line: "Checked counsellors, legal aid, medical services and helplines.",
      },
      {
        title: "Support when you're told to stay quiet",
        line: "Words you can change, if a school, a workplace, or someone close is pressuring you.",
      },
    ],
    howCloseTitle: "You're in control",
    howCloseLine: "Nothing is shared without your permission",
    reminderTitle: "A reminder",
    reminderDots: "Reminders",
    reminders: [
      {
        title: "A reminder",
        body: "If you did not consent, it was not your fault. Not if you froze. Not if you knew them. Not if you waited to tell anyone.",
      },
      {
        title: "A reminder",
        body: "You're allowed to be angry, but not at yourself.",
      },
    ],
    decision: "The decision stays with you.",
    helpNote: "Nia is not an emergency service.",
    allLines: "All helplines",
    callNow: "Call now",
    organisations: "Organisations",
    helplinesTitle: "Helplines in Kenya.",
    helplinesLine: "Each number is labeled, so you know who answers.",
    urgent: {
      title: "If this just happened",
      lede: "You can ask for care even if you are not ready to report. Nia does not give medical advice. Ask the clinician.",
      questions: [
        "Can you treat my injuries?",
        "Can I get emergency contraception?",
        "Can I get medicine to help prevent HIV?",
        "Can a forensic exam be done, and can it be stored if I am not ready to report?",
        "I may have been given something without knowing. Can you check for that?",
      ],
      lines: "1195 is support. It is not the police. MSF is the medical hotline on this page.",
      call: "Call 1195",
    },
    unhcrNote: "Partner offices are listed on the UNHCR Kenya help page.",
    quickLines: [
      { label: "Police", numbers: ["999", "112"] },
      { label: "GBV helpline", numbers: ["1195"] },
      { label: "Under 18", numbers: ["116"] },
    ],
    footer: "Kenya · Adults 18+",
    footerTagline: "Your Voice. Your Rights. Your Support.",
    footerAbout:
      "Free, confidential support for people in Kenya who have faced sexual harassment.",
    footerExplore: "On this site",
    footerHelp: "Talk to someone now",
    footerHome: "Home",
    footerNavLabel: "Footer",
    logIn: "Log in",
    signUp: "Sign up",
    logOut: "Log out",
    accountMenu: "Account",
    profile: "Profile",
    settings: "Settings",
    logoutTitle: "You're leaving.",
    logoutLine: "Are you sure?",
    logoutStay: "Stay signed in",
    logoutConfirm: "Yes, log out",
    account: {
      profileTitle: "Profile",
      profileLine: "This is the name Nia uses for you. Your real name is not stored.",
      profileAnonymous: "Nia chose this name. It is not based on your email.",
      profileChosen: "You chose this name.",
      settingsTitle: "Settings",
      settingsLine: "Change how Nia addresses you.",
      username: "Username",
      email: "Email",
      save: "Save",
      saved: "Saved.",
      openSettings: "Change this name",
      openProfile: "Back to profile",
    },
    record: {
      title: "Your note",
      editTitle: "Edit this note",
      placeholder: "What you remember. The time and the name can be unknown.",
      hint: "Unknown time, a face, or a room is enough.",
      download: "Download a copy",
      downloadNote: "A copy for you. You decide if you share it. Nia does not send this file anywhere.",
      downloadHeading: "A copy for me. I decide if I share it.",
      downloadName: "nia-notes.txt",
      save: "Save note",
      update: "Update note",
      edited: "Edited",
      editHint: "The first note stays. This save adds another, marked Edited.",
      saving: "Saving",
      saved: "Saved. Only you can see this.",
      edit: "Edit",
      remove: "Delete",
      cancel: "Cancel",
      deleteAsk: "Delete this note?",
      signIn: "Sign in to write a private note. Only you can see it.",
      empty: "Your notes will appear here.",
      errors: {
        record_empty: "Write something before you save.",
        record_long: "That note is too long.",
        record_limit: "You have reached the limit for notes.",
        record_missing: "That note is no longer here.",
        invalid_credentials: "Sign in again to see your notes.",
        request_failed: "Something went wrong. Try again.",
      },
    },
    auth: {
      loginTitle: "Log in",
      signupTitle: "Sign up",
      loginLine: "Use the email and password for your Nia account.",
      signupLine: "Create an account. Nia will not ask for your real name.",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm password",
      emailPlaceholder: "Email address",
      passwordPlaceholder: "Password",
      submitLogin: "Log in",
      submitSignup: "Sign up",
      submitting: "Please wait",
      continueGoogle: "Continue with Google",
      or: "or",
      googleNameLine: "Google confirmed your email. Choose how Nia should address you. Your Google name is not used.",
      needAccount: "Need an account?",
      haveAccount: "Already have an account?",
      nameChoice: "How should Nia address you?",
      anonymous: "Use an anonymous name",
      anonymousHint: "Nia will choose a name that is not based on your email.",
      chosen: "Choose a username",
      chosenHint: "Do not use your real name, or a name you use on other sites.",
      username: "Username",
      usernamePlaceholder: "Username",
      visualLine: "You decide what happens next.",
      visualCaption: "Free, confidential support",
      errors: {
        invalid_credentials: "Email or password is incorrect.",
        invalid_email: "Enter a valid email address.",
        password_short: "Use at least 8 characters.",
        password_mismatch: "Passwords do not match.",
        username_taken: "That username is taken. Try another.",
        username_invalid: "Use 3–20 letters, numbers, or hyphens. Do not use an email or a phone number.",
        username_required: "Choose a username, or use an anonymous name.",
        account_unavailable: "Could not create an account with those details.",
        request_failed: "Something went wrong. Try again.",
        google_unavailable: "Google sign-in is not available yet.",
        google_failed: "Google sign-in did not finish. Try again.",
        google_denied: "Google sign-in was cancelled.",
        google_unverified: "That Google account has no verified email.",
        google_expired: "Google sign-in expired. Try again.",
      },
    },
    screens: {
      learn: {
        title: "Recognise it.",
        body: "Sexual harassment is unwanted sexual behaviour. It can be words, pictures, or touch.",
        next: "rights",
        nextLabel: "Rights",
        sectionsTitle: "What it can look like",
        sectionsLede: "You do not have to be sure of the legal name before you ask for support.",
        sections: [
          {
            title: "Words, pictures, and touch",
            body: "It can look like any of these:",
            points: [
              "Comments about your body, your sex life, or what you should do sexually.",
              "Pressure for a date, for sex, or for photos.",
              "Touch you did not agree to.",
              "Someone using a job, a grade, money, or a threat to pressure you.",
              "Intimate images shared without your agreement.",
            ],
          },
          {
            title: "Where it happens",
            body: "At work, at school, at home, online, or in a public place. It can come from a stranger, a partner, a supervisor, or someone you know.",
          },
          {
            title: "It still counts",
            body: "You may have frozen, laughed, stayed, or not said no out loud. You do not need injuries for it to matter.",
          },
        ],
        guide: {
          title: "Help someone",
          lede: "If someone shares an instance of sexual harassment with you, these suggestions are meant to help you support them.",
          sections: [
            {
              title: "Listen",
              body: "Allow the person who is disclosing to guide the conversation.",
            },
            {
              title: "Validate",
              body: "Validate their feelings and give them options. Supportive statements include:",
              points: [
                "I hear you.",
                "This is not your fault.",
                "That sounds like a difficult situation.",
                "How can I best support you right now?",
                "Would you like to talk about it?",
              ],
            },
            {
              title: "Ask how you can help",
              body: "Ask what you can do to assist them:",
              points: [
                "Do they need medical support?",
                "Would they like to go somewhere else, more private, or a different building?",
                "Would they like to contact someone, or have a friend with them?",
              ],
            },
            {
              title: "Be inclusive",
              body: "Sexual harassment can affect anyone. All genders, gender identities, ethnicities, sexual orientations, and backgrounds can experience it.",
            },
            {
              title: "Mention resources",
              body: "Point them to verified lines: the GBV helpline 1195, police 999 or 112, and counselling 1190. Organisations such as COVAW, LVCT, and MSF are on the Helplines page.",
              action: { id: "helplines", label: "Helplines" },
            },
            {
              title: "Be aware of what you say",
              body: "Refrain from judgmental, blaming, or dismissive comments. Do not ask biased questions that can hurt. Hurtful comments include:",
              examples: [
                "How much did you have to drink?",
                "What were you wearing?",
                "Haven’t you gone out with that person before?",
                "That’s not that big of a deal.",
              ],
            },
            {
              title: "Recognise the effects of trauma",
              body: "Trauma affects people in different ways and can affect memory. Someone may be experiencing trauma and not act the way you expect. They may come forward immediately or years later. How long they wait does not change the support they should receive.",
            },
            {
              title: "Respect their privacy",
              body: "Do not tell anyone else what they shared. Do not contact the other people involved, and do not try to investigate on your own.",
            },
            {
              title: "Do not try to fix it",
              body: "Let them decide the next steps, including whether to report to the police or to an organisation. Do not try to mediate, and do not discourage them from making a report.",
            },
            {
              title: "Seek self-care",
              body: "Someone sharing this can be hard for them and for you. Take care of yourself, and seek support if you need it. The same helplines are there for you.",
            },
          ],
        },
      },
      rights: {
        title: "Know your options.",
        body: "These are options people in Kenya use. Nia does not give legal advice, and Nia does not decide for you.",
        next: "helplines",
        nextLabel: "Get help",
        sectionsTitle: "You choose the next step",
        sectionsLede: "You can use one of these, several, or none. Waiting does not erase what happened.",
        sections: [
          {
            title: "Take your time",
            body: "You do not have to report today. You can learn, talk to someone, get medical care, or wait until you are ready.",
          },
          {
            title: "Medical care",
            body: "A hospital or clinic can treat injuries and offer emergency care. You can ask for care even if you are not ready to speak to the police.",
            action: { id: "helplines", anchor: "just-happened", label: "Questions you can ask" },
          },
          {
            title: "The police",
            body: "You can report sexual violence to the police. Call 999 or 112 if you are in danger, or go to a station when you are ready. Reporting is your choice.",
          },
          {
            title: "Work or school",
            body: "A workplace or a college process is not the police. It can look at whether someone broke their rules. The police look at whether a crime may have happened. You can use one, both, or neither.",
            points: [
              "At work, an employer with 20 or more employees must have a sexual harassment policy under Kenya’s Employment Act. You can tell them. You can also choose not to.",
              "A college or university may have its own office. You can ask what that office does before you give your name.",
              "Delay, and pressure to withdraw, are common. You can ask for the steps in writing. You do not have to agree to meet the people involved.",
              "A lawyer or a legal aid organisation can talk about your own situation. Organisations are on the Helplines page. Nia does not choose one for you.",
            ],
            action: { id: "complicated", anchor: "words-you-can-use", label: "Words you can use" },
          },
          {
            title: "A confidential line",
            body: "The national GBV helpline is 1195. Counselling is 1190. These lines are for support. They are not the police.",
          },
          {
            title: "Not legal advice",
            body: "A law can depend on the facts, and procedures change. A lawyer, a legal aid organisation, or a helpline can talk about your own situation. Nia only lists options.",
          },
        ],
      },
      support: {
        title: "Reach someone verified.",
        body: "Official lines are in Helplines. Each one is labeled.",
        next: "helplines",
        nextLabel: "Helplines",
      },
      document: {
        title: "A private record.",
        body: "A short note can help you remember. A fragment is enough. Sign in to keep it here. Only you can see it.",
        bodySignedIn: "A short note can help you remember. A fragment is enough. Only you can see what you write here.",
        next: "home",
        nextLabel: "Home",
        sectionsTitle: "What to write down",
        sectionsLede: "Write it somewhere only you can open. Do not send it to the person who harmed you.",
        sections: [
          {
            title: "The facts you still remember",
            body: "Include what you can:",
            points: [
              "The date, time, and place, if you know them. Unknown is enough.",
              "What you remember, even out of order. A face, a room, or waking up somewhere else.",
              "What the person said or did.",
              "Who else was there.",
              "Messages, photos, or emails you still have. Keep them. Do not send them back.",
              "How it affected you, including sleep, work, or your body.",
            ],
          },
          {
            title: "Nothing here is saved",
            body: "Sign in to keep a note on your account. Until you do, nothing on this page is saved.",
            guestOnly: true,
          },
          {
            title: "Why a note can help",
            body: "Memory can change after a frightening event. A note made soon after can help if you later speak to a doctor, an employer, or the police. You never have to use it.",
          },
        ],
      },
      complicated: {
        title: "You do not have to sort all of it today.",
        body: "If it was recent, medical care comes first. You can write down the pieces you remember. You can call a line that is not the police.",
        next: "helplines",
        nextLabel: "Get help",
        sectionsTitle: "What you can do today",
        sectionsLede: "One step is enough.",
        sections: [
          {
            title: "Medical care, if it was recent",
            body: "You can ask a clinician to treat injuries, offer emergency contraception and medicine to help prevent HIV, and talk about a forensic exam that can be stored if you are not ready to report. You can also say you may have been given something.",
            action: { id: "helplines", anchor: "just-happened", label: "Questions you can ask" },
          },
          {
            title: "Write the pieces you remember",
            body: "You do not need the time, the order, or a name. A face, a room, or waking up somewhere else is enough.",
            action: { id: "document", label: "Private record" },
          },
          {
            title: "Call a line that is not the police",
            body: "The national GBV helpline is 1195. It is for support. You do not have to report.",
            action: { id: "helplines", label: "Helplines" },
          },
          {
            title: "If people are pressuring you",
            body: "You do not have to answer them.",
            points: [
              "Use a phone and an account that you control.",
              "You can save messages without replying.",
              "Tell one person you trust where you are.",
            ],
          },
        ],
        scripts: {
          title: "Words you can use",
          lede: "You do not have to send any of these. Change them so they say what you mean. Do not send them to the people who harmed you. Nothing here is saved.",
          copy: "Copy",
          copied: "Copied.",
          copyFailed: "Select the words and copy them.",
          items: [
            {
              id: "update",
              title: "To a school or employer",
              body: "I am asking for an update on what I reported. Please reply in writing. I do not agree to meet the people involved.",
            },
            {
              id: "friend",
              title: "To a friend or your family",
              body: "I need your support. Please do not ask me questions about what happened. I will tell you if I want to talk.",
            },
            {
              id: "stop",
              title: "If you want contact to stop",
              body: "Do not contact me again.",
            },
          ],
        },
      },
    },
  },
  sw: {
    skip: "Ruka hadi maudhui",
    help: "Nahitaji msaada",
    exit: "Toka haraka",
    helpBar: "Bure, faragha, saa 24",
    nav: [
      { id: "helplines", label: "Pata msaada" },
      { id: "learn", label: "Jifunze" },
      { id: "rights", label: "Haki" },
      { id: "document", label: "Kumbukumbu" },
    ],
    eyebrow: "Msaada wa bure, wa faragha",
    heroTitle: "Wewe unaamua kinachofuata.",
    heroLine:
      "Nia ni kwa watu wazima Kenya waliokumbana na unyanyasaji wa kingono. Jifunze, ona chaguo zako, na ufikie nambari iliyothibitishwa, kwa wakati wako.",
    ctaReach: "Pata msaada sasa",
    channelNumber: "1195",
    channelCaption: "Simu ya GBV",
    channels: [
      { image: "/images/portrait.png", label: "Piga" },
      { image: "/images/conversation.png", label: "Zungumza" },
      { image: "/images/support.png", label: "Tibiwa" },
    ],
    iWantTitle: "Nataka…",
    paths: [
      {
        id: "helplines",
        title: "Pata msaada sasa",
        line: "Piga nambari yenye jina. Utajua nani anapokea.",
      },
      {
        id: "support-someone",
        title: "Msaidie mtu ninayemjali",
        line: "Mtu akikueleza yaliyotokea, hivi ndivyo ya kusikiliza.",
      },
      {
        id: "rights",
        title: "Jua chaguo zangu",
        line: "Taarifa zenye chanzo. Nia haiamui badala yako.",
      },
      {
        id: "document",
        title: "Weka kumbukumbu ya faragha",
        line: "Andiko la faragha kwenye akaunti yako. Wewe peke yako unaweza kukiona.",
      },
      {
        id: "complicated",
        title: "Kitu kigumu kimetokea",
        line: "Watu zaidi ya mmoja, kutiwa dawa, au shinikizo kutoka chuoni au kazini.",
      },
    ],
    howTitle: "Nia inasaidiaje",
    howLine: "Wewe unaamua kinachofuata, kwa mwendo wako.",
    how: [
      {
        title: "Elewa kilichotokea",
        line: "Tambua unyanyasaji na matumizi mabaya ya mamlaka. Si kosa lako kamwe.",
      },
      {
        title: "Jua haki zako",
        line: "Sheria ya Kenya kwa lugha rahisi, iliyokaguliwa dhidi ya vyanzo rasmi.",
      },
      {
        title: "Weka kumbukumbu ya faragha",
        line: "Andika kilichotokea. Ni wewe pekee unayeiona, isipokuwa ukishiriki.",
      },
      {
        title: "Watu wengi huambiwa wanyamaze",
        line: "Unaweza kuweka majina kwenye andiko lako la faragha. Nia haiyalinganishi na ya mtu mwingine.",
      },
      {
        title: "Fikia msaada uliothibitishwa",
        line: "Washauri, msaada wa kisheria, huduma za matibabu na nambari za msaada zilizokaguliwa.",
      },
      {
        title: "Msaada unapoambiwa unyamaze",
        line: "Maneno unayoweza kubadilisha, shule, mahali pa kazi, au mtu wa karibu akikushinikiza.",
      },
    ],
    howCloseTitle: "Uko kwenye udhibiti",
    howCloseLine: "Hakuna kinachoshirikiwa bila ruhusa yako",
    reminderTitle: "Ukumbusho",
    reminderDots: "Vikumbusho",
    reminders: [
      {
        title: "Ukumbusho",
        body: "Ikiwa hukukubali, haikuwa kosa lako. Hata kama uliganda. Hata kama uliwajua. Hata kama ulichelewa kumwambia mtu.",
      },
      {
        title: "Ukumbusho",
        body: "Unaruhusiwa kuwa na hasira, lakini si kwako mwenyewe.",
      },
    ],
    decision: "Uamuzi uko kwako.",
    helpNote: "Nia si huduma ya dharura.",
    allLines: "Nambari zote",
    callNow: "Piga sasa",
    organisations: "Mashirika",
    helplinesTitle: "Nambari za msaada Kenya.",
    helplinesLine: "Kila nambari ina jina, ujue nani anapokea.",
    urgent: {
      title: "Ikiwa hii imetokea sasa hivi",
      lede: "Unaweza kuomba matibabu hata kama hujajiandaa kuripoti. Nia haitoi ushauri wa matibabu. Muulize daktari.",
      questions: [
        "Je, unaweza kutibu majeraha yangu?",
        "Je, naweza kupata uzazi wa mpango wa dharura?",
        "Je, naweza kupata dawa ya kusaidia kuzuia HIV?",
        "Je, uchunguzi wa ushahidi unaweza kufanywa, na kuhifadhiwa ikiwa bado sijajiandaa kuripoti?",
        "Huenda nilipewa kitu bila kujua. Je, unaweza kukagua hilo?",
      ],
      lines: "1195 ni msaada. Si polisi. MSF ndiyo simu ya matibabu kwenye ukurasa huu.",
      call: "Piga 1195",
    },
    unhcrNote: "Ofisi za washirika ziko kwenye ukurasa wa UNHCR Kenya.",
    quickLines: [
      { label: "Polisi", numbers: ["999", "112"] },
      { label: "Simu ya GBV", numbers: ["1195"] },
      { label: "Chini ya miaka 18", numbers: ["116"] },
    ],
    footer: "Kenya · Miaka 18+",
    footerTagline: "Sauti yako. Haki zako. Msaada wako.",
    footerAbout:
      "Msaada wa bure, wa faragha kwa watu wazima Kenya waliokumbana na unyanyasaji wa kingono.",
    footerExplore: "Kwenye tovuti hii",
    footerHelp: "Zungumza na mtu sasa",
    footerHome: "Mwanzo",
    footerNavLabel: "Kijachini",
    logIn: "Ingia",
    signUp: "Jisajili",
    logOut: "Toka",
    accountMenu: "Akaunti",
    profile: "Wasifu",
    settings: "Mipangilio",
    logoutTitle: "Unatoka.",
    logoutLine: "Una uhakika?",
    logoutStay: "Baki umeingia",
    logoutConfirm: "Ndio, toka",
    account: {
      profileTitle: "Wasifu",
      profileLine: "Hili ndilo jina Nia inalolitumia. Jina lako halisi halijahifadhiwa.",
      profileAnonymous: "Nia ilichagua jina hili. Halitokani na barua pepe yako.",
      profileChosen: "Ulichagua jina hili.",
      settingsTitle: "Mipangilio",
      settingsLine: "Badilisha jinsi Nia inavyokuita.",
      username: "Jina la mtumiaji",
      email: "Barua pepe",
      save: "Hifadhi",
      saved: "Imehifadhiwa.",
      openSettings: "Badilisha jina hili",
      openProfile: "Rudi kwenye wasifu",
    },
    record: {
      title: "Andiko lako",
      editTitle: "Hariri andiko hili",
      placeholder: "Unachokumbuka. Saa na jina vinaweza kuwa havijulikani.",
      hint: "Saa isiyojulikana, uso, au chumba kinatosha.",
      download: "Pakua nakala",
      downloadNote: "Nakala yako. Wewe unaamua kama utaishiriki. Nia haitumi faili hii popote.",
      downloadHeading: "Nakala yangu. Mimi naamua kama nitaishiriki.",
      downloadName: "nia-notes.txt",
      save: "Hifadhi andiko",
      update: "Sasisha andiko",
      edited: "Imehaririwa",
      editHint: "Andiko la kwanza linabaki. Hifadhi hii inaongeza lingine, lenye alama Imehaririwa.",
      saving: "Inahifadhi",
      saved: "Imehifadhiwa. Wewe peke yako unaweza kukiona.",
      edit: "Hariri",
      remove: "Futa",
      cancel: "Ghairi",
      deleteAsk: "Futa andiko hili?",
      signIn: "Ingia ili kuandika andiko la faragha. Wewe peke yako utaweza kukiona.",
      empty: "Kumbukumbu zako zitaonekana hapa.",
      errors: {
        record_empty: "Andika kitu kabla ya kuhifadhi.",
        record_long: "Andiko hilo ni refu sana.",
        record_limit: "Umefika kikomo cha andiko.",
        record_missing: "Andiko hilo halipo tena.",
        invalid_credentials: "Ingia tena ili kuona andiko zako.",
        request_failed: "Hitilafu imetokea. Jaribu tena.",
      },
    },
    auth: {
      loginTitle: "Ingia",
      signupTitle: "Jisajili",
      loginLine: "Tumia barua pepe na nenosiri la akaunti yako ya Nia.",
      signupLine: "Fungua akaunti. Nia haitauliza jina lako halisi.",
      email: "Barua pepe",
      password: "Nenosiri",
      confirmPassword: "Rudia nenosiri",
      emailPlaceholder: "Barua pepe",
      passwordPlaceholder: "Nenosiri",
      submitLogin: "Ingia",
      submitSignup: "Jisajili",
      submitting: "Tafadhali subiri",
      continueGoogle: "Endelea na Google",
      or: "au",
      googleNameLine: "Google imethibitisha barua pepe yako. Chagua jinsi Nia itakavyokuita. Jina lako la Google halitumiwi.",
      needAccount: "Huna akaunti?",
      haveAccount: "Una akaunti tayari?",
      nameChoice: "Nia ikuitaje?",
      anonymous: "Tumia jina la faragha",
      anonymousHint: "Nia itachagua jina lisilotokana na barua pepe yako.",
      chosen: "Chagua jina la mtumiaji",
      chosenHint: "Usitumie jina lako halisi, wala jina unalotumia kwenye tovuti nyingine.",
      username: "Jina la mtumiaji",
      usernamePlaceholder: "Jina la mtumiaji",
      visualLine: "Wewe unaamua kinachofuata.",
      visualCaption: "Msaada wa bure, wa faragha",
      errors: {
        invalid_credentials: "Barua pepe au nenosiri si sahihi.",
        invalid_email: "Weka barua pepe sahihi.",
        password_short: "Tumia angalau herufi 8.",
        password_mismatch: "Manenosiri hayafanani.",
        username_taken: "Jina hilo la mtumiaji limechukuliwa. Jaribu lingine.",
        username_invalid: "Tumia herufi 3–20, nambari, au vistari. Usitumie barua pepe au nambari ya simu.",
        username_required: "Chagua jina la mtumiaji, au tumia jina la faragha.",
        account_unavailable: "Haikuwezekana kufungua akaunti kwa maelezo hayo.",
        request_failed: "Hitilafu imetokea. Jaribu tena.",
        google_unavailable: "Kuingia kwa Google bado hakujafika.",
        google_failed: "Kuingia kwa Google hakukamilika. Jaribu tena.",
        google_denied: "Kuingia kwa Google kumesitishwa.",
        google_unverified: "Akaunti hiyo ya Google haina barua pepe iliyothibitishwa.",
        google_expired: "Kuingia kwa Google kumekwisha muda. Jaribu tena.",
      },
    },
    screens: {
      learn: {
        title: "Tambua.",
        body: "Unyanyasaji wa kingono ni tabia ya kingono isiyotakikana. Inaweza kuwa maneno, picha, au mguso.",
        next: "rights",
        nextLabel: "Haki",
        sectionsTitle: "Inaweza kuonekanaje",
        sectionsLede: "Huhitaji kuwa na uhakika wa jina la kisheria kabla ya kuomba msaada.",
        sections: [
          {
            title: "Maneno, picha, na mguso",
            body: "Inaweza kuonekana hivi:",
            points: [
              "Maneno kuhusu mwili wako, maisha yako ya kingono, au unachopaswa kufanya kingono.",
              "Shinikizo la miadi, ngono, au picha.",
              "Mguso usioukubali.",
              "Mtu anayetumia kazi, alama, pesa, au tishio kukushinikiza.",
              "Picha za faragha zilizosambazwa bila ridhaa yako.",
            ],
          },
          {
            title: "Inatokea wapi",
            body: "Kazini, shuleni, nyumbani, mtandaoni, au mahali pa umma. Inaweza kutoka kwa mgeni, mpenzi, msimamizi, au mtu unayemfahamu.",
          },
          {
            title: "Bado ina maana",
            body: "Unaweza kuwa umeganda, umecheka, umebaki, au hukusema hapana kwa sauti. Huhitaji majeraha ili iwe na maana.",
          },
        ],
        guide: {
          title: "Msaidie mtu",
          lede: "Mtu akishiriki tukio la unyanyasaji wa kingono, mapendekezo haya yanakusaidia kumsaidia.",
          sections: [
            {
              title: "Sikiliza",
              body: "Mwachie mtu anayeshiriki aongoze mazungumzo.",
            },
            {
              title: "Thibitisha",
              body: "Thibitisha hisia zake na umpe chaguo. Maneno ya kuunga mkono ni pamoja na:",
              points: [
                "Nakusikia.",
                "Hili si kosa lako.",
                "Hiyo inaonekana kuwa hali ngumu.",
                "Ninawezaje kukusaidia vizuri sasa hivi?",
                "Ungependa kuzungumza kuhusu hilo?",
              ],
            },
            {
              title: "Uliza jinsi ya kusaidia",
              body: "Uliza unachoweza kufanya:",
              points: [
                "Je, anahitaji msaada wa matibabu?",
                "Je, angependa kwenda mahali pengine, faragha zaidi, au jengo lingine?",
                "Je, angependa kuwasiliana na mtu, au awe na rafiki?",
              ],
            },
            {
              title: "Kuwa jumuishi",
              body: "Unyanyasaji wa kingono unaweza kumpata mtu yeyote. Jinsia zote, utambulisho wa kijinsia, makabila, mwelekeo wa kingono, na asili zote zinaweza kuukumbana.",
            },
            {
              title: "Taja msaada",
              body: "Waonyeshe nambari zilizothibitishwa: simu ya GBV 1195, polisi 999 au 112, na ushauri 1190. Mashirika kama COVAW, LVCT, na MSF yako kwenye ukurasa wa Nambari.",
              action: { id: "helplines", label: "Nambari" },
            },
            {
              title: "Jihadhari na unachosema",
              body: "Epuka maneno ya kuhukumu, kulaumu, au kudharau. Usiulize maswali yenye upendeleo yanayoweza kuumiza. Maneno yanayoumiza ni pamoja na:",
              examples: [
                "Ulikunywa kiasi gani?",
                "Ulikuwa umevaa nini?",
                "Hukuwahi kutoka na mtu huyo?",
                "Hilo si jambo kubwa.",
              ],
            },
            {
              title: "Tambua athari za kiwewe",
              body: "Kiwewe kinawaathiri watu kwa njia tofauti, na kinaweza kuathiri kumbukumbu. Mtu anaweza kuwa na kiwewe na asitende kama unavyotarajia. Anaweza kuja mara moja au baada ya miaka. Muda haubadilishi msaada anayestahili.",
            },
            {
              title: "Heshimu faragha",
              body: "Usimwambie mtu mwingine alichoshiriki. Usiwasiliane na watu wengine waliohusika, wala usifanye uchunguzi peke yako.",
            },
            {
              title: "Usijaribu kulirekebisha",
              body: "Waache waamue hatua zinazofuata, pamoja na kama wanataka kuripoti kwa polisi au kwa shirika. Usijaribu kupatanisha, wala usiwazuie kutoa taarifa.",
            },
            {
              title: "Jitunze",
              body: "Mtu kushiriki haya kunaweza kuwa kugumu kwake na kwako. Jitunze, na utafute msaada ukihitaji. Nambari zile zile zipo kwa ajili yako pia.",
            },
          ],
        },
      },
      rights: {
        title: "Jua chaguo zako.",
        body: "Haya ni chaguo watu hutumia Kenya. Nia haitoi ushauri wa kisheria, na Nia haiamui badala yako.",
        next: "helplines",
        nextLabel: "Pata msaada",
        sectionsTitle: "Wewe unachagua hatua inayofuata",
        sectionsLede: "Unaweza kutumia moja, kadhaa, au hakuna. Kusubiri hakufuti yaliyotokea.",
        sections: [
          {
            title: "Chukua muda wako",
            body: "Huhitaji kuripoti leo. Unaweza kujifunza, kuzungumza na mtu, kupata matibabu, au kusubiri utakapokuwa tayari.",
          },
          {
            title: "Matibabu",
            body: "Hospitali au kliniki inaweza kutibu majeraha na kutoa huduma ya dharura. Unaweza kuomba matibabu hata kama hujajiandaa kuzungumza na polisi.",
            action: { id: "helplines", anchor: "just-happened", label: "Maswali unayoweza kuuliza" },
          },
          {
            title: "Polisi",
            body: "Unaweza kuripoti unyanyasaji wa kingono kwa polisi. Piga 999 au 112 ukiwa hatarini, au nenda kituoni utakapokuwa tayari. Kuripoti ni chaguo lako.",
          },
          {
            title: "Kazi au shule",
            body: "Mchakato wa kazini au chuoni si polisi. Unaweza kuangalia kama mtu amevunja kanuni zao. Polisi huangalia kama huenda kosa limetokea. Unaweza kutumia moja, vyote viwili, au hakuna.",
            points: [
              "Kazini, mwajiri mwenye wafanyakazi 20 au zaidi lazima awe na sera ya unyanyasaji wa kingono chini ya Sheria ya Ajira ya Kenya. Unaweza kuwaambia. Unaweza pia ukachagua kutowaambia.",
              "Chuo kinaweza kuwa na ofisi yake. Unaweza kuuliza ofisi hiyo hufanya nini kabla ya kutoa jina lako.",
              "Kuchelewa, na shinikizo la kuondoa malalamiko, ni jambo la kawaida. Unaweza kuomba hatua kwa maandishi. Huhitaji kukubali kukutana na watu waliohusika.",
              "Mwanasheria au shirika la msaada wa kisheria linaweza kuzungumzia hali yako. Mashirika yako kwenye ukurasa wa Nambari. Nia haichagui moja kwa ajili yako.",
            ],
            action: { id: "complicated", anchor: "words-you-can-use", label: "Maneno unayoweza kutumia" },
          },
          {
            title: "Simu ya faragha",
            body: "Simu ya kitaifa ya GBV ni 1195. Ushauri ni 1190. Hizi ni kwa msaada. Si polisi.",
          },
          {
            title: "Si ushauri wa kisheria",
            body: "Sheria inaweza kutegemea ukweli, na taratibu hubadilika. Mwanasheria, shirika la msaada wa kisheria, au simu ya msaada inaweza kuzungumzia hali yako. Nia inaorodhesha chaguo tu.",
          },
        ],
      },
      support: {
        title: "Fikia msaada uliothibitishwa.",
        body: "Nambari rasmi ziko kwenye Nambari. Kila moja ina jina.",
        next: "helplines",
        nextLabel: "Nambari",
      },
      document: {
        title: "Kumbukumbu ya faragha.",
        body: "Andiko fupi linaweza kukusaidia kukumbuka. Hata kumbukumbu isiyokamilika inatosha. Ingia ili kuliweka hapa. Wewe peke yako unaweza kukiona.",
        bodySignedIn: "Andiko fupi linaweza kukusaidia kukumbuka. Hata kumbukumbu isiyokamilika inatosha. Wewe peke yako unaweza kuona unachoandika hapa.",
        next: "home",
        nextLabel: "Mwanzo",
        sectionsTitle: "Andika nini",
        sectionsLede: "Andika mahali unapoweza kufungua wewe peke yako. Usimtumie mtu aliyekudhuru.",
        sections: [
          {
            title: "Ukweli unaokumbuka",
            body: "Weka unachoweza:",
            points: [
              "Tarehe, saa, na mahali, ukivijua. Kisichojulikana kinatosha.",
              "Unachokumbuka, hata kama si kwa mpangilio. Uso, chumba, au kuamka mahali pengine.",
              "Mtu alisema nini au alifanya nini.",
              "Nani mwingine alikuwepo.",
              "Ujumbe, picha, au barua pepe bado unazo. Zihifadhi. Usizirudishe.",
              "Ilikuathirije, pamoja na usingizi, kazi, au mwili wako.",
            ],
          },
          {
            title: "Hakuna kinachohifadhiwa hapa",
            body: "Ingia ili kuweka andiko kwenye akaunti yako. Kabla ya kuingia, hakuna kinachohifadhiwa kwenye ukurasa huu.",
            guestOnly: true,
          },
          {
            title: "Kwa nini andiko linaweza kusaidia",
            body: "Kumbukumbu inaweza kubadilika baada ya tukio linalotisha. Andiko la muda mfupi baadaye linaweza kusaidia ukizungumza na daktari, mwajiri, au polisi. Huhitaji kulitumia.",
          },
        ],
      },
      complicated: {
        title: "Huhitaji kuyapanga yote leo.",
        body: "Ikiwa imetokea karibuni, matibabu yanakuja kwanza. Unaweza kuandika vipande unavyokumbuka. Unaweza kupiga simu ambayo si polisi.",
        next: "helplines",
        nextLabel: "Pata msaada",
        sectionsTitle: "Unachoweza kufanya leo",
        sectionsLede: "Hatua moja inatosha.",
        sections: [
          {
            title: "Matibabu, ikiwa imetokea karibuni",
            body: "Unaweza kumuomba daktari atibu majeraha, atoe uzazi wa mpango wa dharura na dawa ya kusaidia kuzuia HIV, na azungumzie uchunguzi wa ushahidi unaoweza kuhifadhiwa ikiwa hujajiandaa kuripoti. Unaweza pia kusema huenda ulipewa kitu.",
            action: { id: "helplines", anchor: "just-happened", label: "Maswali unayoweza kuuliza" },
          },
          {
            title: "Andika vipande unavyokumbuka",
            body: "Huhitaji saa, mpangilio, wala jina. Uso, chumba, au kuamka mahali pengine kinatosha.",
            action: { id: "document", label: "Kumbukumbu" },
          },
          {
            title: "Piga simu ambayo si polisi",
            body: "Simu ya kitaifa ya GBV ni 1195. Ni kwa msaada. Huhitaji kuripoti.",
            action: { id: "helplines", label: "Nambari" },
          },
          {
            title: "Watu wakikushinikiza",
            body: "Huhitaji kuwajibu.",
            points: [
              "Tumia simu na akaunti unazodhibiti.",
              "Unaweza kuhifadhi ujumbe bila kujibu.",
              "Mwambie mtu mmoja unayemwamini ulipo.",
            ],
          },
        ],
        scripts: {
          title: "Maneno unayoweza kutumia",
          lede: "Huhitaji kutuma lolote kati ya haya. Yabadilishe yaseme unachomaanisha. Usiwatumie watu waliokudhuru. Hakuna kinachohifadhiwa hapa.",
          copy: "Nakili",
          copied: "Imenakiliwa.",
          copyFailed: "Chagua maneno na uyanakili.",
          items: [
            {
              id: "update",
              title: "Kwa shule au mwajiri",
              body: "Ninaomba taarifa kuhusu nilichoripoti. Tafadhali jibu kwa maandishi. Sikubali kukutana na watu waliohusika.",
            },
            {
              id: "friend",
              title: "Kwa rafiki au familia yako",
              body: "Nahitaji msaada wako. Tafadhali usiniulize maswali kuhusu yaliyotokea. Nitakuambia nikitaka kuzungumza.",
            },
            {
              id: "stop",
              title: "Ukitaka mawasiliano yakome",
              body: "Usiwasiliane nami tena.",
            },
          ],
        },
      },
    },
  },
};

export default copy;
